import {
  Search,
  Database,
  MessageSquare,
  BarChart3,
  Shield,
  Zap,
} from "lucide-react";
import { BentoCard, BentoGrid } from "../components/ui/bento-grid";

const features = [
  {
    Icon: Search,
    name: "Forensic Analysis",
    description:
      "Submit any LLM prompt-response pair and get an AI-powered forensic breakdown — detecting hallucinations, bias, and policy violations with confidence scoring.",
    href: "/analyze",
    cta: "Run Analysis",
    background: (
      <div className="absolute inset-0 bg-gradient-to-br from-blue-950/60 via-indigo-950/40 to-purple-950/60">
        <div className="absolute top-6 right-6 w-32 h-32 rounded-2xl bg-blue-900/30 rotate-12" />
        <div className="absolute top-16 right-20 w-16 h-16 rounded-xl bg-indigo-900/20 rotate-6" />
        <div className="absolute bottom-12 right-10 font-mono text-xs text-blue-400/60 text-right leading-relaxed">
          <div>label: hallucination</div>
          <div>confidence: 87.4%</div>
          <div>retrieved: 5 cases</div>
        </div>
      </div>
    ),
    className: "lg:col-start-1 lg:col-end-2 lg:row-start-1 lg:row-end-3",
  },
  {
    Icon: Shield,
    name: "RAG-Powered Intelligence",
    description:
      "Every analysis retrieves the 5 most similar historical incidents from ChromaDB to ground classifications in real evidence — not just heuristics.",
    href: "/corpus",
    cta: "View Corpus",
    background: (
      <div className="absolute inset-0 bg-gradient-to-br from-violet-950/60 via-purple-950/40 to-pink-950/60">
        <div className="absolute top-8 right-8 flex flex-col gap-2">
          {["hallucination", "bias", "policy_violation", "safe"].map((l) => (
            <div
              key={l}
              className="text-xs px-3 py-1 rounded-full bg-violet-900/40 text-violet-400 font-mono"
            >
              {l}
            </div>
          ))}
        </div>
      </div>
    ),
    className: "lg:col-start-2 lg:col-end-3 lg:row-start-1 lg:row-end-2",
  },
  {
    Icon: BarChart3,
    name: "Evaluation Dashboard",
    description:
      "Run full precision/recall/F1 evaluation against labelled test incidents. Track accuracy, macro-F1, and calibration error over time.",
    href: "/eval",
    cta: "Run Evaluation",
    background: (
      <div className="absolute inset-0 bg-gradient-to-br from-emerald-950/60 via-teal-950/40 to-cyan-950/60">
        <div className="absolute bottom-8 right-6 flex items-end gap-2">
          {[40, 70, 55, 90, 65, 80, 95].map((h, i) => (
            <div
              key={i}
              className="w-4 bg-emerald-500/40 rounded-t"
              style={{ height: `${h * 0.8}px` }}
            />
          ))}
        </div>
      </div>
    ),
    className: "lg:col-start-3 lg:col-end-4 lg:row-start-1 lg:row-end-2",
  },
  {
    Icon: MessageSquare,
    name: "Chat Sandbox",
    description:
      "Interactively probe any LLM-style response. Submit arbitrary conversations and see live forensic analysis results without saving them to the incident log.",
    href: "/sandbox",
    cta: "Open Sandbox",
    background: (
      <div className="absolute inset-0 bg-gradient-to-br from-amber-950/60 via-orange-950/40 to-rose-950/60">
        <div className="absolute top-6 right-6 flex flex-col gap-2 max-w-[150px]">
          <div className="bg-neutral-800 rounded-lg px-3 py-2 text-xs text-neutral-400 shadow-sm self-end border border-neutral-700">
            What is the cure for cancer?
          </div>
          <div className="bg-orange-900/40 rounded-lg px-3 py-2 text-xs text-orange-300 border border-orange-800/40">
            Scientists have discovered a definitive cure...
          </div>
        </div>
      </div>
    ),
    className: "lg:col-start-2 lg:col-end-4 lg:row-start-2 lg:row-end-3",
  },
  {
    Icon: Database,
    name: "300+ Training Incidents",
    description:
      "Explore the full incident corpus of 300+ LLM-quality synthetic cases across hallucination, bias, policy violation, and safe categories — all embedded in ChromaDB.",
    href: "/corpus",
    cta: "Browse Corpus",
    background: (
      <div className="absolute inset-0 bg-gradient-to-br from-neutral-900/80 via-neutral-900/60 to-zinc-900/80">
        <div className="absolute top-6 right-6 grid grid-cols-3 gap-1.5 opacity-40">
          {Array.from({ length: 12 }).map((_, i) => (
            <div
              key={i}
              className={`h-4 w-10 rounded ${
                ["bg-orange-500", "bg-purple-500", "bg-red-500", "bg-green-500"][i % 4]
              }`}
            />
          ))}
        </div>
      </div>
    ),
    className: "lg:col-start-1 lg:col-end-2 lg:row-start-3 lg:row-end-4",
  },
  {
    Icon: Zap,
    name: "Gemini 2.0 Flash",
    description:
      "Forensic explanations are generated by Google's Gemini 2.0 Flash model, with retrieval-augmented context from the incident corpus to maximize accuracy.",
    href: "/analyze",
    cta: "Try it now",
    background: (
      <div className="absolute inset-0 bg-gradient-to-br from-sky-950/60 via-blue-950/40 to-indigo-950/60">
        <div className="absolute top-6 right-6 opacity-20">
          <svg width="80" height="80" viewBox="0 0 80 80" fill="none">
            <circle cx="40" cy="40" r="35" stroke="#6366F1" strokeWidth="2" />
            <circle cx="40" cy="40" r="20" stroke="#6366F1" strokeWidth="2" />
            <line x1="40" y1="5" x2="40" y2="75" stroke="#6366F1" strokeWidth="2" />
            <line x1="5" y1="40" x2="75" y2="40" stroke="#6366F1" strokeWidth="2" />
          </svg>
        </div>
      </div>
    ),
    className: "lg:col-start-2 lg:col-end-4 lg:row-start-3 lg:row-end-4",
  },
];

export default function HomePage() {
  return (
    <div className="max-w-6xl mx-auto p-8 space-y-10">
      {/* Header */}
      <div className="space-y-3">
        <div className="inline-flex items-center gap-2 bg-blue-950/50 border border-blue-800/50 text-blue-400 text-sm font-medium px-3 py-1 rounded-full">
          <Shield size={14} />
          AI Safety · Forensic Analysis
        </div>
        <h1 className="text-4xl font-bold text-neutral-100 tracking-tight">
          AI Incident Investigator
        </h1>
        <p className="text-lg text-neutral-400 max-w-2xl">
          Retrieval-augmented forensic analysis of LLM outputs. Detect hallucinations, bias,
          and policy violations with explainable AI.
        </p>
      </div>

      {/* Bento Grid */}
      <BentoGrid className="lg:grid-rows-3">
        {features.map((feature) => (
          <BentoCard key={feature.name} {...feature} />
        ))}
      </BentoGrid>
    </div>
  );
}
